[theme]
primaryColor="#E03617"  # Color principal
backgroundColor="#10111C"  # Color de fondo
secondaryBackgroundColor="#5F6176"  # Color de fondo secundario
textColor="#ECECEC"  # Color del texto
font="sans serif"  # Fuente de texto


                